### ISSUE TITLE
Install prepare-kali.sh errors

### ISSUE THREAD

**Issue by scaery** [mgeeky/Penetration-Testing-Tools#1]
Ohai, tried this on a vanilla kali 2019.4 and encountered some prequisites missing.

1. Docker debian keyring required else docker-ce cannot be installed trough apt
`apt install -y debian-keyring`

2. lanmaster53 recon-ng repo is no more on bitbucket, it is on github instead line 266
`https://github.com/lanmaster53/recon-ng`

3. mitmproxy 5.0.0.dev0 has requirement certifi 2017.7.27.1 + ldap3 2.5.1 which is incompatible.
`apt install -y tox`
`pip3 install -U pip`
`pip3 install mitmproxy`
or
`apt install -y mitmproxy`

4. ruby mysql error Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
`apt install -y libmariadb-dev`

5. screenshot util in ~/tools/web/httpscreenshot - Failed building wheel for m2crypto with pip
`apt install -y python-m2crypt`

6. s3 has a bunch of depency errors

Everything else is straight forward. Thanks for sharing your pentest arsenal. Highly appreciated :)

**Comment by mgeeky** [comment]
Hi @scaery! Thanks for your bug report. I've added some fixes and changed `docker` installation strategy entirely to accommodate later additions to Kali packages repository.

Hope the script will work more stable now :)

**Comment by scaery** [comment]
Awesome. Thanks

You have a typo in line 67: python-m2crypt to python-m2crypto

**Comment by mgeeky** [comment]
You're totally right, I've just took the shortcut and copied-pasted your solution. Fixed the typo now in [e3fc9a5e](https://github.com/mgeeky/Penetration-Testing-Tools/commit/e3fc9a5e0edc8e5098b24199458786f166573cb3). I'd rather stay away from mangling with `pip` as long as it works fine on my Kali instance provisioned with this script. 

If you forsee any further issues with that pip installation - could you please do some tests first, pointing out where it may come short and what do we do about that in a stable manner?

Best regards,
M.

**Comment by mgeeky** [comment]
(close the issue by mistake :< )

**Comment by scaery** [comment]
Now it works like a charm ;)

[Closed]
