### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cfroystad** [mgeeky/Penetration-Testing-Tools#4]
This is a goldmine of useful scripts, thank you!

May I suggest that you add a license to the repository so that we may [use it legally](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)?

Feel free to close if you don't want to add a license 🙂

**Comment by mgeeky** [comment]
Ah snag, that's yet another oversight from my side 🙂

Thanks a lot for this suggestion and for your apprecation - MIT License is now added.
Feel free to use whatever you need wherever you need!

Regards,
Mariusz.
